// Pig
class PigNew : AetheriusMorphedMonster replaces Pig
{
	default
	{
		Tag "Pig";
		Health 25;
		Painchance 128;
		Painchance "Fist", 192; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 255; // Kick attacks have a +150% chance of stunning an enemy
		Painchance "Gauntlets", 192; // Fist attacks have a +50% chance of stunning an enemy
		DamageFactor 0.5;
		RadiusDamageFactor 0.5;
		DamageFactor "Explosion", 0.5;
		DamageFactor "Crush", 4.0;
		Speed 10;
		Radius 12;
		Height 22;
		Mass 60;
		Monster;
		-COUNTKILL;
		+WINDTHRUST;
		+DONTMORPH;
		SeeSound "PigActive1";
		PainSound "PigPain";
		DeathSound "PigDeath";
		ActiveSound "PigActive1";
	}
	
	States
	{
		Spawn:
			PIGY B 0 NoDelay;
			PIGY B 10 A_Look();
			goto Spawn+1;
		See:
			PIGY A 0;
			PIGY ABCD 3
			{
				if (levelbehavior && user_monsterlevel > 90) { A_SetTics(2); }
				A_DVDSChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Melee:
			TNT1 A 0;
			PIGY A 5 A_FaceTarget();
			PIGY A 10 
			{
				A_FaceTarget();;
				
				A_CrisisMeleeAttack(random[PigAttack](2, 3), "PigAttack");
			}
			Goto See;
		Pain:
			PIGY D 4 A_PigPain();
			Goto See;
		Death:
			TNT1 A 0 A_DVDSNormalDeath(-2,0,1);
			PIGY E 4 A_Scream();
			PIGY F 3 A_NoBlocking();
			PIGY G 4 A_QueueCorpse();
			PIGY H 3;
			PIGY IJK 4; 
			PIGY L -1;
			Stop;
		Ice:
			#### # 0 A_DVDSIceDeath(-2,0,1);
			PIGY M 5 A_FreezeDeath();
			PIGY M 1 A_FreezeDeathChunks();
			Wait;
	}
}
class FPig : PigNew
{
	default
	{
		-COUNTKILL;
		+FRIENDLY;
		+THRUSPECIES;
		+DONTHARMSPECIES;
		Species "FriendlyMonsters";
		dropitem "NoItemSpawn", 1;
	}
}

class EttinNew : AetheriusMonsterZSC // replaces Ettin
{
	default
	{
		Tag "Ettin";
		Health 175;
		Radius 25;
		Height 68;
		Mass 175;
		Speed 13;
		Damage 3;
		Painchance 60;
		Painchance "Fist", 90; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 150; // Kick attacks have a +150% chance of stunning an enemy
		Painchance "Gauntlets", 90; // Fist attacks have a +50% chance of stunning an enemy
		DamageFactor "Crush", 1.0;
		Monster;
		MeleeRange 68;
		+FLOORCLIP;
		+TELESTOMP;
		SeeSound "EttinSight";
		AttackSound "EttinAttack";
		PainSound "EttinPain";
		DeathSound "EttinDeath";
		ActiveSound "EttinActive";
		HowlSound "PuppyBeat";
		Obituary "$OB_ETTIN";
	}
	
	States
	{
		Spawn:
			ETTN A 0 NoDelay;
			ETTN AA 10 A_Look();
			goto Spawn+1;
		See:
			ETTN A 0;
			ETTN ABCD 5
			{
				if (levelbehavior && user_monsterlevel > 45) { A_SetTics(4); }
				if (levelbehavior && user_monsterlevel > 90) { A_SetTics(3); }
				A_DVDSChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Melee:
			TNT1 A 0;
			ETTN EF 6
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
			}
			ETTN G 8 
			{
				if (levelbehavior && user_monsterlevel > 120) { A_SetTics(6); }
				else if (levelbehavior && user_monsterlevel > 60) { A_SetTics(7); }
				A_FaceTarget();
				
				A_CrisisMeleeAttack(random[EttinAttack](1,8)*2);
			}
			Goto See;
		Pain:
			ETTN H 7 A_DVDSPain();
			Goto See;
		Pain.Fist:
			ETTN H 7 A_DVDSPain();
			ETTN H 7;
			Goto See;
		Pain.Kick:
			ETTN H 7 A_DVDSPain();
			ETTN HH 7;
			Goto See;
		Death:
			TNT1 A 0 A_DVDSNormalDeath(-2,0,1);
			ETTN IJ 4;
			ETTN K 4 A_Scream();
			ETTN L 4 A_NoBlocking();
			ETTN M 4 A_QueueCorpse();
			ETTN NOP 4;
			ETTN Q -1;
			Stop;

		XDeath:
			TNT1 A 0 A_DVDSNormalDeath(-2,0,1);
			ETTB A 4;
			ETTB B 4 A_NoBlocking();
			ETTB C 4 A_SpawnItemEx("EttinMace", 0, 0, 8.5, random[DropMace](-128, 127)*0.03125, random[DropMace](-128, 127)*0.03125, 10+random[DropMace](0, 255)*0.015625, 0, SXF_ABSOLUTEVELOCITY);
			ETTB D 4 A_Scream();
			ETTB E 4 A_QueueCorpse();
			ETTB FGHIJK 4;
			TNT1 A 0;
			ETTB L -1;
			Stop;
		Ice:
			#### # 0 A_DVDSIceDeath(-2,0,1);
			ETTN R 5 A_FreezeDeath();
			ETTN R 1 A_FreezeDeathChunks();
			Wait;
		Raise:
			ETTN P 4;
			ETTN ONMLKJI 4;
			Goto See;
	}
}
class FEttin : EttinNew
{
	default
	{
		-COUNTKILL;
		+FRIENDLY;
		+THRUSPECIES;
		+DONTHARMSPECIES;
		Species "FriendlyMonsters";
		dropitem "NoItemSpawn", 1;
	}
}

class EttinGhostNew : EttinNew replaces EttinMash
{
	default
	{
		Tag "Ettin (Ghost)";
		+NOBLOOD;
		+NOICEDEATH;
		RenderStyle "Translucent";
		Alpha 0.4;
		DamageFactor "Eldritch", 0.4;
	}
	
	States
	{
		Death:
		XDeath:
		Ice:
			#### # 0 A_DVDSIceDeath(-2,0,1);
			TNT1 A 3;
			Stop;
	}
}

// Ettin Commander [ported from Wrath of Cronos]
class EttinCommander : EttinNew
{
	default
	{
		Tag "Ettin Commander";
		Health 275;
		Mass 250;
		Speed 15;
		Damage 4;
		Painchance 35;
		Painchance "Fist", 52; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 87; // Kick attacks have a +150% chance of stunning an enemy
		Painchance "Gauntlets", 52; // Fist attacks have a +50% chance of stunning an enemy
		MeleeRange 68;
		DamageFactor 0.875;
		RadiusDamageFactor 0.875;
		DamageFactor "Explosive", 0.875;
		DamageFactor "Magic", 1.142857143;
		DamageFactor "Crush", 1.0;
		Translation "81:96=81:88", "97:121=97:109";
		Monster;
		+FLOORCLIP;
		+TELESTOMP;
		+NODAMAGETHRUST;
		+MISSILEMORE;
		Obituary "%o was smashed by an Ettin Commander.";
	}
	
	States
	{
		Spawn:
			CETN A 0 NoDelay;
			CETN AA 10 A_Look();
			goto Spawn+1;
		See:
			CETN A 0;
			CETN ABCD 5
			{
				if (levelbehavior && user_monsterlevel > 45) { A_SetTics(4); }
				if (levelbehavior && user_monsterlevel > 90) { A_SetTics(3); }
				A_DVDSChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Pain:
			CETN H 7 A_DVDSPain();
			Goto See;
		Pain.Fist:
			CETN H 7 A_DVDSPain();
			CETN H 7;
			Goto See;
		Pain.Kick:
			CETN H 7 A_DVDSPain();
			CETN HH 7;
			Goto See;
		Melee:
			TNT1 A 0;
			CETN EF 6
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
			}
			CETN G 8 
			{
				if (levelbehavior && user_monsterlevel > 120) { A_SetTics(6); }
				else if (levelbehavior && user_monsterlevel > 60) { A_SetTics(7); }
				A_FaceTarget();

				A_MonsterCrisisCheck(); // Combo Attack
				A_CrisisComboAttack("ThrownMace","ThrownMaceCrisis",52,(random(2,8)*4));
			}
			Goto See;
		Missile:
			TNT1 A 0;
			CETN EF 6
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
			}
			CETN G 8 
			{
				if (levelbehavior && user_monsterlevel > 120) { A_SetTics(6); }
				else if (levelbehavior && user_monsterlevel > 60) { A_SetTics(7); }
				A_FaceTarget();

				A_StartSound("FighterHammerMiss");
				A_MonsterCrisisCheck(); // Combo Attack
				A_CrisisComboAttack("ThrownMace","ThrownMaceCrisis",52,(random(2,8)*4));
			}
			Goto See;

		Death:
			TNT1 A 0 A_DVDSNormalDeath(-2,0,1);
			CETN IJ 4;
			CETN K 4 A_Scream();
			CETN L 4 A_NoBlocking();
			CETN M 4 A_QueueCorpse();
			CETN NO 4;
			CETN P 4;
			CETN Q -1; //A_DVDSBossDeath();
			Stop;

		XDeath:
			TNT1 A 0 A_DVDSNormalDeath(-2,0,1);
			CETB A 4; //A_SpawnItemEx("GIBBER");
			CETB B 4 A_NoBlocking();
			CETB C 4 A_SpawnItemEx("EttinMace", 0,0,8.5, random[DropMace](-128,127) * 0.03125, random[DropMace](-128,127) * 0.03125, 10 + random[DropMace](0,255) * 0.015625, 0, SXF_ABSOLUTEMOMENTUM);
			CETB D 4 A_Scream();
			CETB E 4 A_QueueCorpse();
			CETB FGHIJ 4;
			CETB K 4;
			ETTB L -1; //A_DVDSBossDeath();
			Stop;
		Ice:
			#### # 0 A_DVDSIceDeath(-2,0,1);
			---- E 5 A_GenericFreezeDeath();
			---- E 1 A_FreezeDeathChunks();
			Wait;
		Raise:
			CETN P 4;
			CETN ONMLKJI 4;
			Goto See;
	}
}
class FEttinCommander : EttinCommander
{
	default
	{
		-COUNTKILL;
		+FRIENDLY;
		+THRUSPECIES;
		+DONTHARMSPECIES;
		Species "FriendlyMonsters";
		dropitem "NoItemSpawn", 1;
	}
}

// Bormereth :V
class Bormereth : AetheriusMonsterZSC
{
	default
	{
		Tag "Bormereth";
		Health 1200;
		Radius 30;
		Height 64;
		Speed 10;
		PainChance 75;
		Painchance "Fist", 112; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 187; // Kick attacks have a +150% chance of stunning an enemy
		Painchance "Gauntlets", 112; // Fist attacks have a +50% chance of stunning an enemy
		DamageFactor 0.75;
		RadiusDamageFactor 0.1875;
		DamageFactor "Explosive", 0.1875;
		DamageFactor "Crush", 0.4;
		Mass 2500;
		BloodColor "Red";
		MeleeRange 68;
		MONSTER ;
		Meleedamage 8;
		+MISSILEEVENMORE;
		+FLOORCLIP;
		+BOSS;
		SeeSound "DMage/Attack";
		PainSound "DMage/Pain";
		ActiveSound "DMage/idle";
		DeathSound "DMage/death";
		Obituary "%o was incinerated by the rage of a Bormereth.";
		HitObituary "%o was smashed by a Bormereth.";
	}
	
	States
	{
		Spawn:
			BORM A 0 NoDelay;
			BORM A 10 A_Look();
			Loop;
		See:
			BORM A 0;
			BORM AABBCCDD 4
			{
				user_bormpainreact = 0;
				if (levelbehavior && user_monsterlevel > 60) { bAVOIDMELEE = true; A_SetTics(3); }
				A_DVDSChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Missile:
			BORM A 0;
			TNT1 A 0 A_Jump(60,"Missile2");
			TNT1 A 0 A_Jump(128,"Missile1b");
			BORM EF 6
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
			}
			BORM G 6 Bright 
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("bormereth/missilesimple",CHAN_5);

				A_MonsterCrisisCheck(); // Single Projectile
				A_CrisisSpawnProjectile("BormerethFX1","BormerethFX1Crisis",25,0,0);
			}
			BORM EF 6
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
			}
			BORM G 6 Bright 
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("bormereth/missilesimple",CHAN_5);

				A_MonsterCrisisCheck(); // Single Projectile
				A_CrisisSpawnProjectile("BormerethFX1","BormerethFX1Crisis",25,0,0);
			}
			BORM EF 6
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
			}
			BORM G 6 Bright 
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("bormereth/missilesimple",CHAN_5);

				A_MonsterCrisisCheck(); // Single Projectile
				A_CrisisSpawnProjectile("BormerethFX1","BormerethFX1Crisis",25,0,0);
			}
			BORM EF 6
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
			}
			BORM G 6 Bright 
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("bormereth/missilesimple",CHAN_5);

				A_MonsterCrisisCheck(); // Single Projectile
				A_CrisisSpawnProjectile("BormerethFX1","BormerethFX1Crisis",25,0,0);
			}
			Goto See;

		Missile1b:
			TNT1 A 0 A_Jump(128,"Missile1c");
			BORM E 6
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
			}
			BORM F 3
			{
				if (levelbehavior && user_monsterlevel > 90) { A_SetTics(2); }
				A_FaceTarget();
			}
			BORM F 3 Bright
			{
				if (levelbehavior && user_monsterlevel > 90) { A_SetTics(2); }
				A_FaceTarget();
				A_StartSound("bormereth/missilesimple",CHAN_5);

				A_MonsterCrisisCheck(); // Single Projectile
				A_CrisisSpawnProjectile("BormerethFX1","BormerethFX1Crisis",31,10,0);
			}
			BORM G 3 Bright
			{
				if (levelbehavior && user_monsterlevel > 90) { A_SetTics(2); }
				A_FaceTarget();
				A_StartSound("bormereth/missilesimple",CHAN_5);

				A_MonsterCrisisCheck(); // Single Projectile
				A_CrisisSpawnProjectile("BormerethFX1","BormerethFX1Crisis",28,5,0);
			}
			BORM G 3 Bright
			{
				if (levelbehavior && user_monsterlevel > 90) { A_SetTics(2); }
				A_FaceTarget();
				A_StartSound("bormereth/missilesimple",CHAN_5);

				A_MonsterCrisisCheck(); // Single Projectile
				A_CrisisSpawnProjectile("BormerethFX1","BormerethFX1Crisis",25,0,0);
			}
			Goto See;

		Missile1c:
			BORM EF 6
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
			}
			BORM G 6 Bright
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
				A_StartSound("bormereth/missilesimple",CHAN_5);

				A_MonsterCrisisCheck(); // Multiple Projectiles
				A_CrisisSpawnProjectile("BormerethFX1","BormerethFX1Crisis",25,0,20);
				A_CrisisSpawnProjectile("BormerethFX1","BormerethFX1Crisis",25,0,0);
				A_CrisisSpawnProjectile("BormerethFX1","BormerethFX1Crisis",25,0,-20);
			}
			Goto See;
		Missile2:
			BORM F 5
			{
				if (levelbehavior && user_monsterlevel > 120) { A_SetTics(3); }
				else if (levelbehavior && user_monsterlevel > 60) { A_SetTics(4); }
				A_FaceTarget();
			}
			TNT1 A 0 A_StartSound("bormereth/missile2prepare",CHAN_5);
			TNT1 A 0 A_SpawnItemEx("PossEttFakeFireBall",5,25,64,0,0,0,0,128);
			BORM EEEEE 5
			{
				if (levelbehavior && user_monsterlevel > 120) { A_SetTics(3); }
				else if (levelbehavior && user_monsterlevel > 60) { A_SetTics(4); }
				A_FaceTarget();
			}
			BORM E 3
			{
				if (levelbehavior && user_monsterlevel > 90) { A_SetTics(2); }
				A_FaceTarget();
			}
			TNT1 A 0 
			{
				A_MonsterCrisisCheck(); // Single Projectile
				A_CrisisSpawnProjectile("PossEttFireBall","PossEttFireBallCrisis",64,25,0);
			}
			BORM FG 5
			{
				if (levelbehavior && user_monsterlevel > 120) { A_SetTics(3); }
				else if (levelbehavior && user_monsterlevel > 60) { A_SetTics(4); }
				A_FaceTarget();
			}
			Goto See;
		Melee:
			BORM EF 6
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();
			}
			BORM G 6 
			{
				if (levelbehavior && user_monsterlevel > 150) { A_SetTics(4); }
				else if (levelbehavior && user_monsterlevel > 75) { A_SetTics(5); }
				A_FaceTarget();

				A_MonsterCrisisCheck(); // Combo Attack
				A_CrisisComboAttack("BormerethFX1","BormerethFX1Crisis",randompick(25,28,31),8*random(1,8));
			}
			BORM E 0 A_CPosRefire();
			Goto See;
		Pain:
			TNT1 A 0 
			{
				if (random(1,256) <= 192)
				{
					user_bormpainreact = 1;
					if (bormcountercooldown <= 0)
					{
						A_MonsterCrisisCheck(); // Multiple Projectiles
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,0);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,45);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,90);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,135);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,180);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,225);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,270);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,315);
						bormcountercooldown = randompick(35,52,70);
					}
					else
					{
						bormcountercooldown -= random(0,3);
						if (bormcountercooldown < 0) { bormcountercooldown = 0; }
					}
				}
			}
			BORM H 2 A_DVDSPain();
			BORM H 0
			{
				if (user_bormpainreact) { return resolvestate("PainReact"); }
				return resolvestate(null); 
			}
			Goto See;
		Pain.Fist:
			TNT1 A 0 
			{
				if (random(1,256) <= 112)
				{
					if (bormcountercooldown <= 0)
					{
						A_MonsterCrisisCheck(); // Multiple Projectiles
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,0);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,45);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,90);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,135);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,180);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,225);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,270);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,315);
						bormcountercooldown = randompick(35,52,70);
					}
					else
					{
						bormcountercooldown -= random(0,3);
						if (bormcountercooldown < 0) { bormcountercooldown = 0; }
					}
				}
			}
			BORM H 2 A_DVDSPain();
			BORM HH 2;
			BORM H 0
			{
				if (user_bormpainreact) { return resolvestate("PainReact"); }
				return resolvestate(null); 
			}
			Goto See;
		Pain.Kick:
			TNT1 A 0 
			{
				if (random(1,256) <= 112)
				{
					if (bormcountercooldown <= 0)
					{
						A_MonsterCrisisCheck(); // Multiple Projectiles
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,0);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,45);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,90);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,135);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,180);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,225);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,270);
						A_CrisisSpawnProjectile("FirePillarStarter","FirePillarStarterCrisis",32,0,315);
						bormcountercooldown = randompick(35,52,70);
					}
					else
					{
						bormcountercooldown -= random(0,3);
						if (bormcountercooldown < 0) { bormcountercooldown = 0; }
					}
				}
			}
			BORM H 2 A_DVDSPain();
			BORM HHHH 2;
			BORM H 0
			{
				if (user_bormpainreact) { return resolvestate("PainReact"); }
				return resolvestate(null); 
			}
			Goto See;
		PainReact:
			BORM H 2 
			{
				A_SetInvulnerable();
				bCANTSEEK = true;
			}
			BORM HHHHHHHHHH 2;
			BORM H 2 
			{
				user_bormpainreact = 0;
				A_UnSetInvulnerable();
				bCANTSEEK = false;
			}
			Goto See;
		Death:
			TNT1 A 0 A_DVDSNormalDeath(-2,0,1);
			BORM I 5;
			BORM J 5 A_Scream();
			BORM K 5 A_NoBlocking();
			BORM L 5 A_Fall();
			BORM MNO 5;
			BORM P 5;
			BORM Q -1;
			Stop;
		XDeath:  //I just like this death too much! :P
			TNT1 A 0 A_DVDSNormalDeath(-2,0,1);
			TNT1 A 0 A_StartSound("misc/gibbed");
			BORB A 5 A_Scream();
			BORB B 5 A_SpawnItemEx("DBigEttinMace", 0, 0, 32, 3, 0, 0, -90, 128);
			BORB C 5 A_NoBlocking();
			BORB D 5 A_Fall();
			BORB EFGHIJ 5;
			BORB K 5;
			BORB L -1;
			Stop;
		Raise:
			BORM Q 5;
			BORM PONMLKJI 5;
			Goto See;
	}
}
class FBormereth : Bormereth
{
	default
	{
		-COUNTKILL;
		+FRIENDLY;
		+THRUSPECIES;
		+DONTHARMSPECIES;
		Species "FriendlyMonsters";
		dropitem "NoItemSpawn", 1;
	}
}

// Centaurs
class CentaurNew : AetheriusMonsterZSC replaces Centaur
{
	default
	{
		Tag "Centaur";
		Health 200;
		Painchance 135;
		Painchance "Fist", 201; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 255; // Kick attacks have a +150% chance of stunning an enemy
		Painchance "Gauntlets", 201; // Fist attacks have a +50% chance of stunning an enemy
		DamageFactor 0.875;
		RadiusDamageFactor 0.875;
		DamageFactor "Explosion", 0.875;
		DamageFactor "Plasma", 2;
		DamageFactor "Shock", 3;
		DamageFactor "Electric", 3;
		DamageFactor "Thunder", 3;
		DamageFactor "Crush", 1.0;
		Speed 13;
		Height 64;
		Mass 120;
		MeleeRange 80;
		Monster;
		+FLOORCLIP;
		+TELESTOMP;
		+SHIELDREFLECT;
		SeeSound "CentaurSight";
		AttackSound "CentaurAttack";
		PainSound "CentaurPain";
		DeathSound "CentaurDeath";
		ActiveSound "CentaurActive";
		HowlSound "PuppyBeat";
		Obituary "$OB_CENTAUR";
	}

	States
	{
		Spawn:
			CENT A 0 NoDelay;
			CENT AB 10 A_Look();
			goto Spawn+1;
		See:
			CENT A 0;
			CENT ABCD 4
			{
				if (levelbehavior && user_monsterlevel > 60) { A_SetTics(3); }
				A_CentaurShieldOff();
				A_SlaughtaurShieldOff();
				A_DVDSChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Melee:
			TNT1 A 0;
			CENT H 5 
			{
				if (levelbehavior && user_monsterlevel > 120) { A_SetTics(3); }
				else if (levelbehavior && user_monsterlevel > 60) { A_SetTics(4); }
				A_FaceTarget();
			}
			CENT I 4 
			{
				if (levelbehavior && user_monsterlevel > 180) { A_SetTics(2); }
				else if (levelbehavior && user_monsterlevel > 90) { A_SetTics(3); }
				A_FaceTarget();
			}
			CENT J 7
			{
				if (levelbehavior && user_monsterlevel > 120) { A_SetTics(5); }
				else if (levelbehavior && user_monsterlevel > 60) { A_SetTics(6); }
				A_FaceTarget();
				
				A_CrisisMeleeAttack(random[CentaurAttack](3, 9));
			}
			Goto See;
		Pain:
			CENT G 6 A_DVDSPain();
			Goto ShieldDefend;
		Pain.Fist:
			CENT G 6 A_DVDSPain();
			CENT GG 6;
			Goto ShieldDefend;
		Pain.Kick:
			CENT G 6 A_DVDSPain();
			CENT GGGG 6;
			Goto ShieldDefend;
		ShieldDefend:
			CENT G 1 // A_SetReflectiveInvulnerable()
			{
				A_CentaurShieldOn();
				A_FaceTarget();

				if (random(1,128) <= 1) { user_defendtimer += 1; }
				if (random(1,32) <= 1) { user_defendtimer += 1; }
				if (random(1,8) <= 1) { user_defendtimer += 1; }
				user_defendtimer += 1;

				if (levelbehavior && user_monsterlevel > 270) { user_defendtimermax = 3; }
				else if (levelbehavior && user_monsterlevel > 180) { user_defendtimermax = 4; }
				else if (levelbehavior && user_monsterlevel > 90) { user_defendtimermax = 5; }
				else { user_defendtimermax = 6; }

				if (user_defendtimer >= user_defendtimermax) { user_defendtimer = 0; return resolvestate("ShieldBlocking"); }
				return resolvestate(null);
			}
			Loop;
		ShieldBlocking:
			// Defense Cycles
			CENT E 1 // A_CentaurDefend
			{
				A_CentaurShieldOn();
				user_defendtimer += 1;

				if (levelbehavior && user_monsterlevel > 180) { user_defendtimermax = random(17,18); }
				else if (levelbehavior && user_monsterlevel > 120) { user_defendtimermax = random(16,17); }
				else if (levelbehavior && user_monsterlevel > 60) { user_defendtimermax = random(15,16); }
				else { user_defendtimermax = 15; }

				if (user_defendtimer >= user_defendtimermax)
				{
					user_defendtimer = 0;
					user_defendcycles += 1;
					if (random(1,8) == 1 && A_JumpIfTargetInsideMeleeRange("Melee"))
					{
						A_CentaurShieldOff();
						A_SlaughtaurShieldOff();
						return resolvestate("Melee");
					}
					A_FaceTarget();
				}
				if (user_defendcycles >= 3) { return resolvestate("ShieldEnding"); }
				return resolvestate(null);
			}
			Loop;
		ShieldEnding:
			CENT E 1 // A_UnsetReflectiveInvulnerable
			{
				A_CentaurShieldOff();
				A_SlaughtaurShieldOff();
				A_FaceTarget();
			}
			Goto See;

		Death:
			TNT1 A 0 A_DVDSNormalDeath(-2,0,1);
			CENT K 4;
			CENT L 4 A_Scream();
			CENT MN 4;
			CENT O 4 A_NoBlocking();
			CENT PQ 4;
			CENT R 4 A_QueueCorpse();
			CENT S 4;
			CENT T -1;
			Stop;

		XDeath:
			TNT1 A 0 A_DVDSNormalDeath(-2,0,1);
			CTXD A 4;
			CTXD B 4 A_NoBlocking();
			CTXD C 0 A_SpawnItemEx("CentaurSword", 0, 0, 45, 1 + random[CentaurDrop](-128,127)*0.03125,1 + random[CentaurDrop](-128,127)*0.03125, 8 + random[CentaurDrop](0,255)*0.015625, 270);
			CTXD C 4 
			{
				if (random(1,256) == 1)
				{
					A_SpawnProjectile("EvilWarriorShield",44,-32,90,0);
				}
				else
				{
					A_SpawnItemEx("CentaurShield", 0, 0, 45, 1 + random[CentaurDrop](-128,127)*0.03125,
												1 + random[CentaurDrop](-128,127)*0.03125, 8 + random[CentaurDrop](0,255)*0.015625, 90);
				}
			}
			CTXD D 3 A_Scream();
			CTXD E 4 A_QueueCorpse();
			CTXD F 3;
			CTXD G 4;
			CTXD H 3;
			CTXD I 4;
			CTXD J 3;
			CTXD K -1;
			stop;
		Ice:
			#### # 0 A_DVDSIceDeath(-2,0,1);
			CENT U 5 A_FreezeDeath();
			CENT U 1 A_FreezeDeathChunks();
			Wait;
		Raise:
			CENT T 4;
			CENT SRQPONMLK 4;
			Goto See;
	}
}
class FCentaur : CentaurNew
{
	default
	{
		-COUNTKILL;
		+FRIENDLY;
		+THRUSPECIES;
		+DONTHARMSPECIES;
		Species "FriendlyMonsters";
		dropitem "NoItemSpawn", 1;
	}
}

class CentaurGhostNew : CentaurNew replaces CentaurMash
{
	default
	{
		Tag "Centaur (Ghost)";
		+NOBLOOD;
		+BLASTED;
		-TELESTOMP;
		+NOICEDEATH;
		RenderStyle "Translucent";
		Alpha 0.4;
		DamageFactor "Eldritch", 0.4;
	}
	
	States
	{
		Death:
		XDeath:
			#### # 0 A_DVDSNormalDeath(-2,0,1);
			TNT1 A 3;
			Stop;
		Ice:
			#### # 0 A_DVDSIceDeath(-2,0,1);
			TNT1 A 3;
			Stop;
	}
}

class SlaughtaurNew : CentaurNew replaces CentaurLeader
{
	default
	{
		Tag "Slaughtaur";
		Health 325;
		Speed 12.5;
		MeleeRange 80;
		Painchance 84;
		Painchance "Fist", 126; // Fist attacks have a +50% chance of stunning an enemy
		Painchance "Kick", 210; // Kick attacks have a +150% chance of stunning an enemy
		Painchance "Gauntlets", 126; // Fist attacks have a +50% chance of stunning an enemy
		DamageFactor 0.75;
		RadiusDamageFactor 0.75;
		DamageFactor "Explosive", 0.75;
		DamageFactor "Fire", 0.75;
		DamageFactor "Magic", 1.1167;
		DamageFactor "Plasma", 2;
		DamageFactor "Thunder", 3;
		DamageFactor "Electric", 3;
		DamageFactor "Lightning", 3;
		DamageFactor "Crush", 1.0;
		
		Translation "81:96=85:92", "97:121=101:113", "0:32=231:235", "33:50=231:235";  // Dark Skin, Obsidian Armor
	}
	
	States
	{
		Melee:
			TNT1 A 0;
			CENT H 5 
			{
				if (levelbehavior && user_monsterlevel > 120) { A_SetTics(3); }
				else if (levelbehavior && user_monsterlevel > 60) { A_SetTics(4); }
				A_FaceTarget();
			}
			CENT I 4 
			{
				if (levelbehavior && user_monsterlevel > 180) { A_SetTics(2); }
				else if (levelbehavior && user_monsterlevel > 90) { A_SetTics(3); }
				A_FaceTarget();
			}
			CENT J 7
			{
				if (levelbehavior && user_monsterlevel > 120) { A_SetTics(5); }
				else if (levelbehavior && user_monsterlevel > 60) { A_SetTics(6); }
				A_FaceTarget();
				
				A_CrisisMeleeAttack(random[CentaurAttack](5, 13));
			}
			Goto See;
		Missile:
			TNT1 A 0;
		MissilePhase1:
			CENT E 1
			{
				A_SlaughtaurShieldOn();
				A_FaceTarget();
				user_defendtimer += 1;

				if (levelbehavior && user_monsterlevel > 180) { user_defendtimermax = random(7,8); }
				else if (levelbehavior && user_monsterlevel > 120) { user_defendtimermax = random(8,9); }
				else if (levelbehavior && user_monsterlevel > 60) { user_defendtimermax = random(9,10); }
				else { user_defendtimermax = 10; }

				if (user_defendtimer >= user_defendtimermax) { user_defendtimer = 0; return resolvestate("MissilePhase2"); }
				return resolvestate(null); 
			}
			Loop;
		MissilePhase2:
			CENT F 1 Bright 
			{
				A_SlaughtaurShieldOn();
				A_FaceTarget();
				user_defendtimer += 1;
				if (user_defendtimer == 1) 
				{
					A_MonsterCrisisCheck(); // Single Projectile
					A_CrisisSpawnProjectile("CentaurFXNew", "CentaurFXCrisis", 45, 0, 0, CMF_AIMOFFSET); 
				}

				if (levelbehavior && user_monsterlevel > 270) { user_defendtimermax = random(5,6); }
				else if (levelbehavior && user_monsterlevel > 180) { user_defendtimermax = random(6,7); }
				else if (levelbehavior && user_monsterlevel > 90) { user_defendtimermax = random(7,8); }
				else { user_defendtimermax = 8; }

				if (user_defendtimer >= user_defendtimermax) { user_defendtimer = 0; return resolvestate("MissilePhase3"); }
				return resolvestate(null); 
			}
			Loop;
		MissilePhase3:
			CENT E 1
			{
				A_SlaughtaurShieldOn();
				A_FaceTarget();
				user_defendtimer += 1;
	
				if (levelbehavior && user_monsterlevel > 180) { user_defendtimermax = random(7,8); }
				else if (levelbehavior && user_monsterlevel > 120) { user_defendtimermax = random(8,9); }
				else if (levelbehavior && user_monsterlevel > 60) { user_defendtimermax = random(9,10); }
				else { user_defendtimermax = 10; }
	
				if (user_defendtimer >= user_defendtimermax) { user_defendtimer = 0; return resolvestate("MissilePhase4"); }
				return resolvestate(null); 
			}
			Loop;
		MissilePhase4:
			CENT F 1 Bright 
			{
				A_SlaughtaurShieldOn();
				A_FaceTarget();
				user_defendtimer += 1;
				if (user_defendtimer == 1) 
				{
					A_MonsterCrisisCheck(); // Single Projectile
					A_CrisisSpawnProjectile("CentaurFXNew", "CentaurFXCrisis", 45, 0, 0, CMF_AIMOFFSET); 
				}
			
				if (levelbehavior && user_monsterlevel > 270) { user_defendtimermax = random(5,6); }
				else if (levelbehavior && user_monsterlevel > 180) { user_defendtimermax = random(6,7); }
				else if (levelbehavior && user_monsterlevel > 90) { user_defendtimermax = random(7,8); }
				else { user_defendtimermax = 8; }
	
				if (user_defendtimer >= user_defendtimermax) 
				{
					A_CentaurShieldOff();
					A_SlaughtaurShieldOff();
					return resolvestate("See"); 
				}
				return resolvestate(null); 
			}
			Loop;
		Pain:
			CENT G 5 A_DVDSPain();
			Goto ShieldDefend;
		Pain.Fist:
			CENT G 5 A_DVDSPain();
			CENT GG 5;
			Goto ShieldDefend;
		Pain.Kick:
			CENT G 5 A_DVDSPain();
			CENT GGGG 5;
			Goto ShieldDefend;
		ShieldDefend:
			CENT G 1 // A_SetReflectiveInvulnerable()
			{
				A_SlaughtaurShieldOn();
				A_FaceTarget();
	
				if (random(1,32) == 1) { user_defendtimer += 1; }
				if (random(1,8) == 1) { user_defendtimer += 1; }
				user_defendtimer += 1;
	
				if (levelbehavior && user_monsterlevel > 315) { user_defendtimermax = 2; }
				else if (levelbehavior && user_monsterlevel > 210) { user_defendtimermax = 3; }
				else if (levelbehavior && user_monsterlevel > 105) { user_defendtimermax = 4; }
				else { user_defendtimermax = 5; }
	
				if (user_defendtimer >= user_defendtimermax) { user_defendtimer = 0; return resolvestate("ShieldBlocking"); }
				return resolvestate(null);
			}
			Loop;
		ShieldBlocking:
			// Defense Cycles
			CENT E 1 // A_CentaurDefend
			{
				A_SlaughtaurShieldOn();
				user_defendtimer += 1;
	
				if (levelbehavior && user_monsterlevel > 180) { user_defendtimermax = random(21,22); }
				else if (levelbehavior && user_monsterlevel > 120) { user_defendtimermax = random(19,20); }
				else if (levelbehavior && user_monsterlevel > 60) { user_defendtimermax = random(18,19); }
				else { user_defendtimermax = 18; }
	
				if (user_defendtimer >= user_defendtimermax)
				{
					user_defendtimer = 0;
					user_defendcycles += 1;
					if (random(1,8) == 1 && A_JumpIfTargetInsideMeleeRange("Melee"))
					{
						A_CentaurShieldOff();
						A_SlaughtaurShieldOff();
						return resolvestate("Melee");
					}
					A_FaceTarget();
				}
				if (user_defendcycles >= 3) { return resolvestate("ShieldEnding"); }
				return resolvestate(null);
			}
			Loop;
		ShieldEnding:
			CENT E 1 // A_UnsetReflectiveInvulnerable
			{
				A_CentaurShieldOff();
				A_SlaughtaurShieldOff();
				A_FaceTarget();
	
				if (levelbehavior && user_monsterlevel > 180) { user_paintomissile = 1; }
				else if (levelbehavior && user_monsterlevel > 160) { user_paintomissile = 2; }
				else if (levelbehavior && user_monsterlevel > 140) { user_paintomissile = 3; }
				else if (levelbehavior && user_monsterlevel > 120) { user_paintomissile = 4; }
				else if (levelbehavior && user_monsterlevel > 100) { user_paintomissile = 5; }
				else if (levelbehavior && user_monsterlevel > 80) { user_paintomissile = 6; }
				else if (levelbehavior && user_monsterlevel > 60) { user_paintomissile = 7; }
				else if (levelbehavior && user_monsterlevel > 40) { user_paintomissile = 8; }
				else if (levelbehavior && user_monsterlevel > 20) { user_paintomissile = 9; }
				else { user_paintomissile = 10; }
	
				if (random(1,user_paintomissile) == 1) { return resolvestate("Missile"); }
				return resolvestate(null);
			}
			Goto See;
	}
}
class FSlaughtaur : SlaughtaurNew
{
	default
	{
		-COUNTKILL;
		+FRIENDLY;
		+THRUSPECIES;
		+DONTHARMSPECIES;
		Species "FriendlyMonsters";
		dropitem "NoItemSpawn", 1;
	}
}
